import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/button/index.ts',
    'src/accordion/index.ts',
    'src/alert-dialog/index.ts',
    'src/autocomplete/index.ts',
    'src/avatar/index.ts',
    'src/checkbox/index.ts',
    'src/checkbox-group/index.ts',
    'src/collapsible/index.ts',
    'src/combobox/index.ts',
    'src/dialog/index.ts',
    'src/drawer/index.ts',
    'src/field/index.ts',
    'src/fieldset/index.ts',
    'src/form/index.ts',
    'src/input/index.ts',
    'src/menu/index.ts',
    'src/menubar/index.ts',
    'src/meter/index.ts',
    'src/navigation-menu/index.ts',
    'src/number-field/index.ts',
    'src/popover/index.ts',
    'src/preview-card/index.ts',
    'src/progress/index.ts',
    'src/radio/index.ts',
    'src/scroll-area/index.ts',
    'src/select/index.ts',
    'src/separator/index.ts',
    'src/slider/index.ts',
    'src/switch/index.ts',
    'src/tabs/index.ts',
    'src/toast/index.ts',
    'src/toggle/index.ts',
    'src/toggle-group/index.ts',
    'src/toolbar/index.ts',
    'src/tooltip/index.ts',
  ],
  format: ['esm'],
  dts: true,
  clean: true,
  external: ['react', 'react-dom', '@stylexjs/stylex'],
});
